name: Main workflow

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@2a814b57e1a920a0c910a1007b50142423386ff0
        with:
          node-version-file: 'package.json'

      - name: Dependency installation
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Integration tests
        run: npm run test

      - name: Checking typescript types and build app
        run: npm run build

      # semantic-release release only from master branch, so do not be worry
      - name: Publish to NPM
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
