name: Main workflow

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022]
        version: [ 14, 16, 18 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Dependency installation
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Integration tests
        run: npm run test

      - name: Checking typescript types and build app
        run: npm run build

      # semantic-release release only from master branch, so do not be worry
      - name: Publish to NPM
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
